name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      id: setup-msys2
    - uses: mxschmitt/action-tmate@v3
      with:
        msys2-location: ${{ steps.setup-msys2.outputs.msys2-location }}
