name: Build Flutter Engine

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-macos:
    name: macos-latest
    runs-on: macos-latest
    steps:

      - name: Check disk space
        run: |
          mkdir -p flutter/engine/src/out/host_debug/zip_archives/darwin-arm64
          touch flutter/engine/src/out/host_debug/zip_archives/darwin-arm64/impeller_sdk.zip

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: flutter/engine/src/out/host_debug/zip_archives/darwin-arm64/*.zip

  build-ubuntu:
    name: ubuntu
    runs-on: ubuntu-22.04

    steps:

      - name: Test
        run: |
          mkdir -p flutter/engine/src/out/host_debug/zip_archives/linux-x64
          touch flutter/engine/src/out/host_debug/zip_archives/linux-x64/impeller_sdk.zip

      - name: Upload Ubuntu artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-artifacts
          path: flutter/engine/src/out/host_debug/zip_archives/linux-x64/*.zip

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-ubuntu]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: write

    steps:
      - name: Generate release id
        run: |
          echo "RELEASE_ID=build-${{ github.run_number }}" >> $GITHUB_ENV
          find .

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_ID }}
          name: ${{ env.RELEASE_ID }}
          draft: false
          prerelease: false
          files: artifacts/**/*.zip
